apiVersion: v1
kind: Secret
metadata:
  name: app-user-secrets
type: Opaque
data:
  RESEND_API_KEY: {{ .Values.secrets.resendAPIKey | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  DATABASE_URL: {{ .Values.secrets.databaseURL | b64enc | quote }}
  GITHUB_OAUTH_CLIENT_ID: {{ .Values.secrets.githubOAuthClientId | b64enc | quote }}
  GITHUB_OAUTH_CLIENT_SECRET: {{ .Values.secrets.githubOAuthClientSecret | b64enc | quote }}
  GOOGLE_OAUTH_CLIENT_ID: {{ .Values.secrets.googleOAuthClientId | b64enc | quote }}
  GOOGLE_OAUTH_CLIENT_SECRET: {{ .Values.secrets.googleOAuthClientSecret | b64enc | quote }}
  PORT: {{ .Values.secrets.port | toString | b64enc | quote }}
  KAFKA_BROKERS: {{ .Values.secrets.kafkaBrokers | b64enc | quote }}
  FRONTEND_URL: {{ .Values.secrets.frontendURL | b64enc | quote }}
