apiVersion: v1
kind: Secret
metadata:
  name: app-test-secrets
type: Opaque
data:
  CES_URL: {{ .Values.secrets.cesURL | b64enc | quote }}
  PORT: {{ .Values.secrets.port | toString | b64enc | quote }}