apiVersion: v1
kind: Secret
metadata:
  name: app-submission-secrets
type: Opaque
data:
  RESEND_API_KEY: {{ .Values.secrets.resendAPIKey | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  DATABASE_URL: {{ .Values.secrets.databaseURL | b64enc | quote }}
  PORT: {{ .Values.secrets.port | b64enc | quote }}
  KAFKA_BROKERS: {{ .Values.secrets.kafkaBrokers | b64enc | quote }}
  TEST_SERVICE_URL: {{ .Values.secrets.testServiceURL | b64enc | quote }}
  PROBLEM_SERVICE_URL: {{ .Values.secrets.problemServiceURL | b64enc | quote }}
  GEMINI_API_KEY: {{ .Values.secrets.geminiAPIKey | b64enc | quote }}