apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  PORT: {{ .Values.secrets.port | toString | b64enc | quote }}
  SESSION_SECRET: {{ .Values.secrets.sessionSecret | b64enc | quote }}
  NODE_ENV: {{ .Values.secrets.nodeEnv | b64enc | quote }}
  MONGO_URI: {{ .Values.secrets.mongoUri | b64enc | quote }}
  USER_SERVICE: {{ .Values.secrets.userService | b64enc | quote }}
  PROBLEMS_SERVICE: {{ .Values.secrets.problemsService | b64enc | quote }}
  SUBMISSION_SERVICE: {{ .Values.secrets.submissionService | b64enc | quote }}
  TEST_SERVICE: {{ .Values.secrets.testService | b64enc | quote }}
  FRONTEND_URL: {{ .Values.secrets.frontendURL | b64enc | quote }}
  KAFKA_BROKERS: {{ .Values.secrets.kafkaBrokers | b64enc | quote }}