apiVersion: v1
kind: Secret
metadata:
  name: app-problem-secrets
type: Opaque
data:
  RESEND_API_KEY: {{ .Values.secrets.resendAPIKey | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  DATABASE_URL: {{ .Values.secrets.databaseURL | b64enc | quote }}
  PORT: {{ .Values.secrets.port | toString | b64enc | quote }}
  KAFKA_BROKERS: {{ .Values.secrets.kafkaBrokers | b64enc | quote }}
