apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.podName }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.podName }}
    spec:
      containers:
        - name: {{ .Values.deployment.containerName }}
          image: {{ .Values.deployment.imageName }}
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.secrets.port }}
              protocol: TCP
          env:
            - name: RESEND_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-problem-secrets
                  key: RESEND_API_KEY
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-problem-secrets
                  key: JWT_SECRET
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-problem-secrets
                  key: DATABASE_URL
            - name: KAFKA_BROKERS
              valueFrom:
                secretKeyRef:
                  name: app-problem-secrets
                  key: KAFKA_BROKERS
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: app-problem-secrets
                  key: PORT