apiVersion: v1
kind: Secret
metadata:
  name: app-gateway-secrets
type: Opaque
data:
  PORT: {{ .Values.secrets.port | b64enc | quote }}
  USER_SERVICE: {{ .Values.secrets.userService | b64enc | quote  }}
  PROBLEM_SERVICE: {{ .Values.secrets.problemService | b64enc | quote }}
  SUBMISSION_SERVICE: {{ .Values.secrets.submissionService | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  FRONTEND_URL: {{ .Values.secrets.frontendURL | b64enc | quote }}