apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.podName }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.podName }}
    spec:
      containers:
        - name: {{ .Values.deployment.containerName }}
          image: {{ .Values.deployment.imageName }}
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
          restartPolicy: Never
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: app-gateway-secrets
                  key: PORT
            - name: USER_SERVICE
              valueFrom:
                secretKeyRef:
                  name: app-gateway-secrets
                  key: USER_SERVICE
            - name: PROBLEM_SERVICE
              valueFrom:
                secretKeyRef:
                  name: app-gateway-secrets
                  key: PROBLEM_SERVICE
            - name: SUBMISSION_SERVICE
              valueFrom:
                secretKeyRef:
                  name: app-gateway-secrets
                  key: SUBMISSION_SERVICE
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-gateway-secrets
                  key: JWT_SECRET
            - name: FRONTEND_URL
              valueFrom:
                secretKeyRef:
                  name: app-gateway-secrets
                  key: FRONTEND_URL