apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.deployment.serviceName }}
  labels:
    app: {{ .Values.deployment.serviceName }}
spec:
  type:  {{ .Values.deployment.serviceType }}
  selector:
    app: {{ .Values.deployment.podName }}
  ports:
    - port: 80 # container listens
      targetPort: 3001 # forwards it to -
      nodePort: 31516