name: Problem Service Build & Publish Image

on:
  push:
    branches: ['main']
    paths: ['problem-service/**']
  pull_request:
    branches: ['main']
    paths: ['problem-service/**']
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        
      - name: Authenticate (Docker Hub)
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/bit-warriors:problem-service problem-service
      
      - name: Publish Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/bit-warriors:problem-service